#!/usr/bin/env bash
# ============================================================================
# Claude Task System v2 -- Mock Ollama (for testing)
# ============================================================================
# Drop-in replacement for the `ollama` command during tests.
# Handles the `run <model>` subcommand and generates canned output.
#
# Environment Variables:
#   MOCK_OLLAMA_DOWN     -- If "1", simulate Ollama server being down (exit 1)
#   MOCK_RESPONSE_DIR    -- Directory for canned responses (optional)
#   MOCK_OLLAMA_MODEL    -- Expected model name for validation (optional)
#   MOCK_DELAY           -- Seconds to sleep before responding (default: 0)
#   MOCK_LOG             -- If set, append invocation args to this file
#
# Usage (as a test double):
#   export LLM_OLLAMA_COMMAND="$PROJECT_ROOT/test/mock-ollama.sh"
# ============================================================================

set -euo pipefail

# Log invocation if requested
if [[ -n "${MOCK_LOG:-}" ]]; then
    echo "$(date -Iseconds) mock-ollama $*" >> "$MOCK_LOG"
fi

# Simulate server down
if [[ "${MOCK_OLLAMA_DOWN:-}" == "1" ]]; then
    echo "Error: could not connect to ollama app, is it running?" >&2
    exit 1
fi

# Simulate delay
if [[ "${MOCK_DELAY:-0}" -gt 0 ]]; then
    sleep "$MOCK_DELAY"
fi

# Parse subcommand
SUBCOMMAND="${1:-}"
shift || true

case "$SUBCOMMAND" in
    run)
        MODEL="${1:-unknown}"
        shift || true
        # Read prompt from remaining args or stdin
        PROMPT="${*:-}"
        if [[ -z "$PROMPT" ]]; then
            PROMPT="$(cat 2>/dev/null || true)"
        fi

        # Check for canned response
        if [[ -n "${MOCK_RESPONSE_DIR:-}" ]] && [[ -d "$MOCK_RESPONSE_DIR" ]]; then
            for response_file in "${MOCK_RESPONSE_DIR}"/*.md; do
                if [[ -f "$response_file" ]]; then
                    cat "$response_file"
                    exit 0
                fi
            done
        fi

        # Default response
        echo "Mock Ollama response from model: $MODEL"
        echo "This is a test response generated by mock-ollama.sh."
        ;;
    list)
        echo "NAME                 ID           SIZE    MODIFIED"
        echo "qwen3:8b             abc123       4.9 GB  2 days ago"
        echo "qwen2.5-coder:7b     def456       4.7 GB  2 days ago"
        echo "deepseek-r1:8b       ghi789       4.9 GB  2 days ago"
        echo "nemotron-mini:latest  jkl012       5.1 GB  2 days ago"
        echo "nomic-embed-text     mno345       274 MB  2 days ago"
        ;;
    ps)
        echo "NAME    ID    SIZE    PROCESSOR    UNTIL"
        ;;
    *)
        echo "Error: unknown command '$SUBCOMMAND'" >&2
        exit 1
        ;;
esac

exit 0
